### ISSUE TITLE
关于打印输出....

### ISSUE THREAD

**Issue by syjsxxjy** [TevinLi/amWiki#104]
用浏览器自带的打印功能，只能识别出目录，如果没有目录就是空白。
请问有没有什么替代的方法能够转成pdf或者其它文档，有一些资料需要打印出来。

**Comment by syjsxxjy** [comment]
虽然可以通过选中的方式，然后用打印机里的保存为pdf，但是锚图标和脚注的图标，会变得非常大，影响排版。。。请问有什么解决方案嘛？
![26](https://user-images.githubusercontent.com/7524140/32341084-6f05bfd6-c037-11e7-9e2d-83d727ef4f12.jpg)

**Comment by TevinLi** [comment]
网页的打印样式其实早期是专门整过的，后来页面布局的升级被弄坏了一直没修复  

你这个情况也是少了几个打印样式造成的，可以给那几个图标加几个打印样式，打印样式和普通样式没什么区别，就是多套了一层，比如这样
```css
@media print {
    .box {
        width: 100px;
    }
}
```
